# Database can either be 'mongodb' or 'file'.
# If you chose 'json', the plugin will save & read from a local .json data file,
# If you chose 'mongodb', the plugin will connect to the mongodb database you provide.
database: 'file'
mongodb:
  username: ''
  password: ''
  uri: ''
  database: ''